{% set name = "fsspec-reference-maker" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0421904d50aa6271dd546995432d34107fc1aa127d91f17a339d084c6ede5c43

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build: []
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - fsspec
    - ujson
    - numpy
    - xarray
    - zarr
    - packaging

test:
  imports:
    - fsspec_reference_maker
    - fsspec_reference_maker.combine
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/intake/fsspec-reference-maker
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Functions to make reference descriptions for ReferenceFileSystem
  dev_url: https://github.com/intake/fsspec-reference-maker

extra:
  recipe-maintainers:
    - martindurant
    - lsterzinger
